apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: {{ .Values.services.streaming.image }}
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGO_URI
          value: mongodb://mongo:27017/streamingapp
        - name: JWT_SECRET
          value: changeme
---
apiVersion: v1
kind: Service
metadata:
  name: streaming
spec:
  type: ClusterIP
  selector:
    app: streaming
  ports:
  - port: 3002
    targetPort: 3002
